---
- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Create snmpd.conf
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: "{{ snmpd_conf_file }}"
    validate: "{{ snmpd_bin }} -n -f %s"
    mode: 0600
  notify: Restart snmpd

- name: Ensure snmpd is started
  ansible.builtin.service:
    name: "{{ snmpd_service }}"
    state: started
